language: java
jdk:
  - oraclejdk8
# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
      - oracle-java8-installer
before_script: cd simple
script: "mvn clean package"
notifications:
  email:
    recipients:
      - kerner1000@gmail.com
    on_failure: change # default: always
